import {
  AugmentedObjectTypeDefinition,
  AugmentedSchemaAST,
} from './semantic-analyzer/types'

/**
 * Generates the TypeScript code for a permissions SDK based on a zed schema.
 * @param schema The augmented schema AST.
 * @returns The generated TypeScript code as a string.
 */
export function generateSDK(
  schema: AugmentedSchemaAST,
  parserImport = '@schoolai/spicedb-zed-schema-parser/builder',
): string {
  const objectDefs = schema.definitions.filter(
    (def): def is AugmentedObjectTypeDefinition => def.type === 'definition',
  )

  let code = `// Generated by @schoolai/spicedb-zed-schema-parser
// Do not edit manually.

import { PermissionOperations } from '${parserImport}';

// --------------- GENERIC TYPES ---------------

export type Subject<T extends string> = \`\${T}:\${string}\`;
export type Resource<T extends string> = \`\${T}:\${string}\`;

// --------------- RESOURCE TYPES ---------------
`

  for (const def of objectDefs) {
    code += `export type ${toPascalCase(def.name)}Resource = Resource<'${def.name}'>;\n`
  }

  code += '\nexport const permissions = {\n'

  for (const def of objectDefs) {
    if (def.relations.length === 0 && def.permissions.length === 0) {
      continue
    }
    code += `  ${toCamelCase(def.name)}: {\n`
    // Generate grant/revoke operations
    code += generateGrantRevoke(def)
    // Generate check operations
    code += generateCheck(def)
    // Generate find operations
    code += generateFind(def)
    // Generate lookup operations
    code += generateLookup(def)
    code += `  },\n`
  }

  code += '};\n'

  return code
}

function generateGrantRevoke(def: AugmentedObjectTypeDefinition): string {
  const resourceType = `${toPascalCase(def.name)}Resource`
  let code = '    grant: {\n'
  for (const rel of def.relations) {
    const subjectTypeLiterals = [
      ...new Set(rel.types.map(t => `'${t.typeName}'`)),
    ].join(' | ')
    const subjectTypes = `Subject<${subjectTypeLiterals || 'never'}>`
    code += `      ${toCamelCase(rel.name)}: (subject: ${subjectTypes}, resource: ${resourceType}) => PermissionOperations.grant('${rel.name}').subject(subject).resource(resource),\n`
  }
  code += '    },\n'
  code += '    revoke: {\n'
  for (const rel of def.relations) {
    const subjectTypeLiterals = [
      ...new Set(rel.types.map(t => `'${t.typeName}'`)),
    ].join(' | ')
    const subjectTypes = `Subject<${subjectTypeLiterals || 'never'}>`
    code += `      ${toCamelCase(rel.name)}: (subject: ${subjectTypes}, resource: ${resourceType}) => PermissionOperations.revoke('${rel.name}').subject(subject).resource(resource),\n`
  }
  code += '    },\n'
  return code
}

function generateFind(def: AugmentedObjectTypeDefinition): string {
  let code = '    find: {\n'
  for (const rel of def.relations) {
    const pascalRel = toPascalCase(rel.name)
    const subjectTypeLiterals = [
      ...new Set(rel.types.map(t => `'${t.typeName}'`)),
    ].join(' | ')
    const subjectTypes = `Subject<${subjectTypeLiterals || 'never'}>`
    code += `      by${pascalRel}: (subject: ${subjectTypes}) => PermissionOperations.find().relation('${rel.name}').subject(subject),\n`
  }
  code += '    },\n'
  return code
}

function generateCheck(def: AugmentedObjectTypeDefinition): string {
  const resourceType = `${toPascalCase(def.name)}Resource`
  let code = '    check: {\n'

  // Generate permission checks
  for (const perm of def.permissions) {
    const subjectTypeLiterals = [
      ...new Set(perm.inferredSubjectTypes?.map(t => `'${t.typeName}'`)),
    ].join(' | ')
    const subjectTypes = `Subject<${subjectTypeLiterals || 'never'}>`
    code += `      ${toCamelCase(perm.name)}: (subject: ${subjectTypes}, resource: ${resourceType}) => PermissionOperations.check('${perm.name}').subject(subject).resource(resource),\n`
  }

  // Generate relation checks
  for (const rel of def.relations) {
    console.log(`Processing relation ${rel.name} in ${def.name}:`, {
      docComment: rel.docComment,
      types: rel.types,
    })

    const subjectTypeLiterals = [
      ...new Set(rel.types.map(t => `'${t.typeName}'`)),
    ].join(' | ')
    const subjectTypes = `Subject<${subjectTypeLiterals || 'never'}>`

    // Check for @check: override in docComment
    let checkName = `is${toPascalCase(rel.name)}`
    if (rel.docComment) {
      console.log(`Found docComment for ${rel.name}: "${rel.docComment}"`)
      const checkMatch = rel.docComment.match(/@check:\s*(\w+)/)
      if (checkMatch) {
        checkName = checkMatch[1]!
        console.log(`Found @check override: ${checkName}`)
      }
    }

    code += `      ${checkName}: (subject: ${subjectTypes}, resource: ${resourceType}) => PermissionOperations.check('${rel.name}').subject(subject).resource(resource),\n`
  }

  code += '    },\n'
  return code
}

// --------------- LOOKUP OPERATIONS ---------------
// This should put a "lookup" operation for each definition with resources and subjects attributes each.
// Example:
// lookup: {
//   resources: (subject: Subject<string>) => PermissionOperations.lookup('resourcesAccessibleBy').subject(subject),
//   subjects: (resource: Resource<string>) => PermissionOperations.lookup('subjectsWithAccessTo').resource(resource),
// }
// Here are two examples of what they should be able to do, but we need something more generic.
// Example 1:
// PermissionOperations.lookup()
// .subjectsWithAccessTo(`space_old:${spaceId}`)
// .withPermission('collected')
// .ofType('collection')
// .withConsistency(assignResult || '')
// .execute(spice)

// Example 2:
// PermissionOperations.lookup()
// .resourcesAccessibleBy(`collection:${collectionId1}`)
// .withPermission('collected')
// .ofType('space_old')
// .withConsistency(assignResult || '')
// .execute(spice)

// lookup: {
// resources: (subject: Subject<string>) => PermissionOperations.lookup('resourcesAccessibleBy').subject(subject),
//   subjects: (resource: Resource<string>) => PermissionOperations.lookup('subjectsWithAccessTo').resource(resource),
// }

// The lookup operation should be able to lookup resources by subject and subjects by resource.
// Can you think of a pattern that would allow us to generate the lookup operations for each definition with resources and subjects attributes each?
function generateLookup(def: AugmentedObjectTypeDefinition): string {
  let code = '    lookup: {\n'
  const permissionLiterals = [
    ...new Set(def.permissions.map(p => `'${p.name}'`)),
  ].join(' | ')

  for (const operation of ['resources', 'subjects']) {
    const typeLiterals = [
      ...new Set(
        def.relations.flatMap(r => r.types.map(t => `'${t.typeName}'`)),
      ),
    ].join(' | ')

    if (operation === 'resources') {
      const subjectTypes = `Subject<${typeLiterals || 'never'}>`
      code += `      ${operation}: (subject: ${subjectTypes}, permission: ${permissionLiterals}, resourceType: ${typeLiterals}) => PermissionOperations.lookup().resourcesAccessibleBy(subject).withPermission(permission).ofType(resourceType),\n`
    } else {
      const resourceTypes = `Resource<${typeLiterals || 'never'}>`
      code += `      ${operation}: (resource: ${resourceTypes}, permission: ${permissionLiterals}, subjectType: ${typeLiterals}) => PermissionOperations.lookup().subjectsWithAccessTo(resource).withPermission(permission).ofType(subjectType),\n`
    }
  }
  code += '    },\n'
  return code
}

function toPascalCase(name: string): string {
  return name
    .split(/[_\-\s]+/)
    .filter(Boolean)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('')
}

function toCamelCase(name: string): string {
  if (name.length === 0) return name
  return (
    toPascalCase(name).charAt(0).toLowerCase() + toPascalCase(name).slice(1)
  )
}
